import logging
from pathlib import Path
from modules.ig_uploader import upload_to_instagram
from modules.metadata_gen import ReelMetadata

# Set up logging to show debug info in terminal
logging.basicConfig(level=logging.INFO)

video_path = Path("test_ig_video.mp4")

if not video_path.exists():
    print("❌ test_ig_video.mp4 not found. Run the moviepy gen command first.")
    exit(1)

metadata = ReelMetadata(
    caption="This is a test video generated by the automation pipeline! 🎉",
    hashtags="#test #automation #python",
    full_caption="This is a test video generated by the automation pipeline! 🎉\n\n#test #automation #python",
    yt_title="Test Video",
    yt_description="Test Description",
    yt_tags=["test", "automation"],
    cover_timestamp="0.0s"
)

print("Starting IG Upload Test...")
success = upload_to_instagram(video_path, metadata)

if success:
    print("✅ TEST PASSED: Video successfully uploaded to Instagram!")
else:
    print("❌ TEST FAILED: Upload did not complete.")
